FROM webdevops/php-nginx:7.4

ENV WEB_DOCUMENT_ROOT "/app/public"
ENV WORKDIR /app

# Use to Get Every Docker Container Ups
RUN apt-get update \
	&& apt install -y p7zip \
    p7zip-full \
    zip \
    unzip \
    curl \
    gnupg \
    procps

# Install Node
RUN curl -sL https://deb.nodesource.com/setup_12.x  | bash - \
    && apt -y install nodejs \
    && npm install \
    && npm install jquery-easing \
    && npm install magnific-popup \

RUN npm install @fortawesome/fontawesome-free

# Copy HTML File
ADD ./deploy/dev/etc/nginx/nginx.conf /etc/nginx/nginx.conf

# Customize PHP
ENV PHP_DISMOD=ioncube,mongodb
ENV fpm.pool.access.log "/dev/null"
ENV fpm.pool.decorate_workers_output "no"

# Disable services
RUN docker-service-disable postfix \
	&& docker-service-disable ssh \
	&& docker-service-disable syslog \
	&& docker-service-disable dnsmasq