FROM webdevops/php-nginx:7.3

ENV WEB_DOCUMENT_ROOT "/var/www/html/public"

# Use to Get Every Docker Container Ups
RUN apt-get update \
	&& apt install -y p7zip \
    p7zip-full \
    zip \
    unzip \
    curl \
    gnupg

# Install Node
RUN curl -sL https://deb.nodesource.com/setup_11.x  | bash - \
    && apt -y install nodejs \
    && npm install \
    && npm install @fortawesome/fontawesome-free

# Only used in some instances
RUN apt install -y procps

# Copy HTML File
ADD ./dev/etc/nginx/nginx.conf /etc/nginx/nginx.conf

# Customize PHP
ENV PHP_DISMOD=ioncube,mongodb
ENV fpm.pool.access.log "/dev/null"
ENV fpm.pool.decorate_workers_output "no"

# Disable services
RUN docker-service-disable postfix \
	&& docker-service-disable ssh \
	&& docker-service-disable syslog \
	&& docker-service-disable dnsmasq